String getVendorOrdersQuery = '''
query GetVendorOrders{
  getVendorOrders{
    error{
      path
      message
    }
    orders{
      id
      orderNo
      address
      customer{
        id
        name
        phoneNumber
        address
        email
      }
      cartItems{
        id
        name 
        category
        originalPrice
        sellingPrice
        description
        inStock
        imageUrl
        vendor{
          id
          phoneNumber
          address
          email
          storeName
          blocked
          panCardPhotoUrls
          shopPhotoUrl
          admin
        }
      } 
      status
      datePlaced
      updatedDate
      totalPrice
      paymentMode
    }
  }
}
''';
