String getVendorOrdersQuery = '''
query GetVendorOrders{
  getVendorOrders{
    error{
      path
      message
    }
    orders{
      id
      orderNo
      address
      customer{
        id
        name
        phoneNumber
        address
        email
      }
      cartItems{
        inventory{
          id
          name 
          category
          originalPrice
          sellingPrice
          description
          inStock
          imageUrl 
        }
      } 
      status
      datePlaced
      updatedDate
      totalPrice
      paymentMode
      transactionSuccess
    }
  }
}
''';
